# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculating Wold coefficient from ARMA model parameters
#' @description Calculating Wold coefficient from ARMA model parameters
#' @param n number
#' @param a AR model coefficient
#' @param b MA model coefficient
#' @return wold coefficient
#' @examples
#' \dontrun{
#' std::vector<double> a = {0.5, 0.3, 0.2};
#' std::vector<double> b = {0.1, 0.2};
#' int n = 10;
#' armaWold(n, a, b)
#' }
#' @export
armaWold <- function(n, a, b) {
    .Call('_SA24204133_armaWold', PACKAGE = 'SA24204133', n, a, b)
}

